apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensy
  name: sensy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensy
  template:
    metadata:
      labels:
        app: sensy
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: sensy-secret
        image: bhupendrargoud/sensy:788504d
        imagePullPolicy: IfNotPresent
        name: sensy
        ports:
        - containerPort: 8000
