apiVersion: v1
kind: Service
metadata:
  name: sensy-service
spec:
  selector:
    app: sensy
  ports:
    - protocol: TCP
      port: 8000  # External port
      targetPort: 8000  # Internal app port
  type: ClusterIP